"""Type definitions for the council domain."""

from dataclasses import dataclass, field

from src.types import Paper


@dataclass
class SearchQuery:
    """A search query generated by the scan step."""

    query: str
    rationale: str


@dataclass
class Proposal:
    """A research proposal from the propose step."""

    hypothesis: str
    approach: str
    expected_impact: str
    search_queries: list[SearchQuery]
    papers_found: list[Paper]
    raw_response: str


@dataclass
class Critique:
    """A critique from the critique step."""

    concerns: list[str]
    suggestions: list[str]
    overall_assessment: str
    raw_response: str


@dataclass
class ExperimentPlan:
    """A refined plan ready for implementation."""

    description: str
    code_changes_summary: str
    addresses_concerns: list[str]
    raw_response: str


@dataclass
class CouncilResult:
    """Full result of a council deliberation cycle."""

    proposal: Proposal
    critique: Critique
    plan: ExperimentPlan
    new_train_py: str
    implement_raw_response: str
    log: list[dict] = field(default_factory=list)
